version: "3"
services:
  emby-connector:
    image: catchsudheera/emby-library-update-connector:1.0.1
    container_name: emby-connector
    ports:
      - 9400:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X GET -I  http://localhost:8080 | grep 'HTTP/1.1 200' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    restart: always
    networks:
      - media_server_network