version: "3.8"
services:
  emby-connector:
    image: catchsudheera/emby-library-update-connector:1.0.4
    container_name: emby-connector
    ports:
      - 9400:8080
    environment:
      - EMBY_URL=${EMBY_URL}
      - EMBY_ACCESS_TOKEN=${EMBY_ACCESS_TOKEN}
      - EMBY_FULL_REFRESH_TIMEOUT_MINS=${EMBY_FULL_REFRESH_TIMEOUT_MINS}
      - SONARR_MEDIA_DIRECTORIES=${SONARR_MEDIA_DIRECTORIES}
      - RADARR_MEDIA_DIRECTORIES=${RADARR_MEDIA_DIRECTORIES}
    healthcheck:
      test: ["CMD-SHELL", "curl -s -X GET -I  http://localhost:8080/health/ping | grep 'HTTP/1.1 200' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    restart: always
      
